name: Travly
options:
  bundleIdPrefix: com.kevinbuckley.travelplanner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
packages:
  TripCore:
    path: Packages/TripCore
targets:
  Travly:
    type: application
    platform: iOS
    sources:
      - Travly
    dependencies:
      - package: TripCore
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        SWIFT_STRICT_CONCURRENCY: complete
        PRODUCT_BUNDLE_IDENTIFIER: com.kevinbuckley.travelplanner
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: A6VYGLF4DB
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_CFBundleDisplayName: "Travly"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Travly uses your location to quickly add stops near you and track your trip."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Travly matches your photos to trip stops based on location and time."
        INFOPLIST_KEY_CFBundleShortVersionString: "1.0"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "16"
  TravlyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TravlyTests
    dependencies:
      - target: Travly
      - package: TripCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kevinbuckley.travelplanner.tests
        GENERATE_INFOPLIST_FILE: YES
